### ISSUE TITLE
node-gyp rebuild fails on OS X

### ISSUE THREAD

**Issue by lpinca** [alexhultman/uWebSockets#93]
I've installed uws version 0.3.4 with npm and compilation fails:

```bash
$ cat build_log.txt
  CXX(target) Release/obj.target/uws/src/uWS.o
In file included from ../src/uWS.cpp:1:
../src/uWS.h:8:10: fatal error: 'mutex' file not found
#include <mutex>
         ^
1 error generated.
make: *** [Release/obj.target/uws/src/uWS.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/luigi/repos/primus/node_modules/uws
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
```

**Comment by alexhultman** [comment]
The fallback works with no issues, right? I will take a look at this.

**Comment by lpinca** [comment]
Yes fallback works.

**Comment by alexhultman** [comment]
I get the same output. This is on the machine I pre-compile on so there should be a mutex.h.

**Comment by kapouer** [comment]
Gimme your include path for mutex.h :)

**Comment by alexhultman** [comment]
I mean mutex

**Comment by kapouer** [comment]
This looks like a similar problem: http://stackoverflow.com/questions/10308167/when-enabling-c11-with-stdlibc-4-7-clang-error-out-while-gcc-compiles-fine

**Comment by alexhultman** [comment]
I think -stdlib=libc++ has to be a linker option, that's how it selects the std implementation. Mutex is only part of libc++ on OSX

**Comment by alexhultman** [comment]
How do you specify linker flags in the bindings.gyp? "libraries"?

**Comment by kapouer** [comment]
Also, get a useful log:
```
node-gyp --loglevel=silly rebuild
```

**Comment by alexhultman** [comment]
I cannot get it to work. I don't think I have set up node-gyp and stuff correctly on my OS X. I guess we can test this next publish.

**Comment by lpinca** [comment]
This is what I get now:
```
make: *** No rule to make target `Release/obj.target/uws/src/uWS.o', needed by `Release/uws.node'.  Stop.
```

**Comment by kapouer** [comment]
@lpinca could you `cd /path/to/node_modules/uws; node-gyp --loglevel=silly rebuild` please ?

**Comment by lpinca** [comment]
@kapouer I'm using `npm install` from `nodejs/dist` of this repo.
I can post the result when called with `npm --loglevel=silly install` but it contains some sensitive data so I would like to avoid that.

**Comment by kapouer** [comment]
@lpinca hey you have to `make` once before trying `npm install`. Do you see files in `nodes/dist/src` ?

**Comment by lpinca** [comment]
Woops, totally forgot I did `make clean` 😄 .
Here is an excerpt of the log:
```bash
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=uws' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/luigi/.node-gyp/6.1.0/include/node -I/Users/luigi/.node-gyp/6.1.0/src -I/Users/luigi/.node-gyp/6.1.0/deps/uv/include -I/Users/luigi/.node-gyp/6.1.0/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/uws/src/uWS.o.d.raw   -c -o Release/obj.target/uws/src/uWS.o ../src/uWS.cpp
In file included from ../src/uWS.cpp:1:
../src/uWS.h:8:10: fatal error: 'mutex' file not found
#include <mutex>
         ^
1 error generated.
make: *** [Release/obj.target/uws/src/uWS.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/luigi/Desktop/repos/uWebSockets/nodejs/dist
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by kapouer** [comment]
`-std=gnu++0x` looks weird in that command. Could you run the same command `g++ ...` with
`-std=c++11` instead ?

**Comment by lpinca** [comment]
@kapouer it has no effect:

```bash
luigi@macbook:build (master)$ c++ '-DNODE_GYP_MODULE_NAME=uws' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/luigi/.node-gyp/6.1.0/include/node -I/Users/luigi/.node-gyp/6.1.0/src -I/Users/luigi/.node-gyp/6.1.0/deps/uv/include -I/Users/luigi/.node-gyp/6.1.0/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/uws/src/uWS.o.d.raw   -c -o Release/obj.target/uws/src/uWS.o ../src/uWS.cpp
In file included from ../src/uWS.cpp:1:
../src/uWS.h:8:10: fatal error: 'mutex' file not found
#include <mutex>
         ^
1 error generated.
```

**Comment by kapouer** [comment]
And with both flags like `clang++ -std=c++11 -stdlib=libc++ test.cpp` ?

**Comment by lpinca** [comment]
```bash
luigi@macbook:build (master)$ c++ '-DNODE_GYP_MODULE_NAME=uws' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/luigi/.node-gyp/6.1.0/include/node -I/Users/luigi/.node-gyp/6.1.0/src -I/Users/luigi/.node-gyp/6.1.0/deps/uv/include -I/Users/luigi/.node-gyp/6.1.0/deps/v8/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/uws/src/uWS.o.d.raw   -c -o Release/obj.target/uws/src/uWS.o ../src/uWS.cpp
../src/uWS.cpp:158:54: warning: field 'port' will be initialized after field 'master' [-Wreorder]
Server::Server(int port, bool master, string path) : port(port), master(master), path(path)
                                                     ^
../src/uWS.cpp:190:13: error: cannot use 'throw' with exceptions disabled
            throw nullptr; // ERR_LISTEN
            ^
../src/uWS.cpp:621:31: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
            for (int i = 0; i < h.value.second; i++) {
                            ~ ^ ~~~~~~~~~~~~~~
2 warnings and 1 error generated.
```

**Comment by kapouer** [comment]
Somewhat better. Remove `-fno-exceptions` and add `-fexceptions` ?

**Comment by lpinca** [comment]
It works, with the above warnings, but I guess they can be suppressed or ignored.

**Comment by kapouer** [comment]
Now let's find the correct `binding.gyp`... can you replace the Darwin ssection with
```
        ['OS=="darwin"', {
          'cflags_cc': [ '-fexceptions', '-std=c++11', '-stdlib=libc++' ],
          'cflags_cc!': [ '-fno-exceptions' ],
          'cflags!': [ '-fno-exceptions' ],
          'ldflags': [ '-stdlib=libc++' ]
        }],
```
and then with
```
        ['OS=="darwin"', {
          'cflags_cc': [ '-fexceptions', '-std=c++11', '-stdlib=libc++' ],
          'cflags_cc!': [ '-fno-exceptions' ],
          'cflags!': [ '-fno-exceptions' ]
        }],
```
and again with
```
        ['OS=="darwin"', {
          'cflags': [ '-fexceptions', '-std=c++11', '-stdlib=libc++' ],
          'cflags!': [ '-fno-exceptions' ]
        }],
```
You get the idea...

**Comment by lpinca** [comment]
None of these works, but I dind't even try to understand, I've litterally copy pasted these over the existing bindings.gyp.

**Comment by kapouer** [comment]
What fails would tell me what's missing.

**Comment by lpinca** [comment]
it still complains about the 'mutex' file.

**Comment by lpinca** [comment]
I'll dig it further in a bit, also if you are on freenode I'm lpin, so we don't spam here :)

**Comment by kapouer** [comment]
Which channel ?

**Comment by alexhultman** [comment]
I like spam :3

**Comment by alexhultman** [comment]
Is it ldflags_cc?

**Comment by lpinca** [comment]
All the flags seem to be ignored, I'll try again tomorrow.

**Comment by lpinca** [comment]
Ok, found a way to make it work:
```
['OS=="mac"', {
  'xcode_settings': {
    'CLANG_CXX_LANGUAGE_STANDARD':'c++11',
    'GCC_ENABLE_CPP_EXCEPTIONS': 'YES',
    'CLANG_CXX_LIBRARY': 'libc++'
  }
}],
```
there are still a of warnings that we can suppress by removing `-Wreorder` and `-Wsign-compare`, I guess.
